language: node_js
sudo: required
cache: yarn
node_js: "8.11.3"
before_install:
- nvm install 6.2
- nvm use 6.2
before_script:
- npm install -g yarn
- yarn install
script:
- gulp electron-travis
before_deploy:
- export DISPLAY=:99.0
- sudo add-apt-repository -y ppa:ubuntu-wine/ppa
- sudo apt-get update -qq
- sudo apt-get install -y wine1.6 p7zip-full
- unzip -o builds/packed/electron.zip -d builds/unpacked/electron
- gulp electron-packager
deploy:
  provider: releases
  api_key:
    secure: YvS+duWNM4XgTbNTleX7U9PYA6yGrIcWmfWDolxV/kCKFxPDu2QftRsEp3cnxNAZktnzGwDIEK/MkVFavsrBrHWnrOXOpFyTgMNlGNoktbERrH4QHwPrkdtUft6eqvwixs2TW43WWNWRnEH0hxOyVZi/CIBfsAYjBF7BRRIA6Tmkt3lIztYh+7opLkZ2HeYlKiAyd1DgJ/PPWh8F1chW4BLIXe5alWno4rlosnkI9t4tHDyQZ30iXrMxew4KEkPZ7TQQsP/rMhlwPbuX8AtXWoqbYPBG7tf1pYrkWUv99CFgATdzM6HkaC4co+KphNDySry8dgqq1BRVLM2XvwbhSXwKTdZa2iuOwNIPLjpuu6qyqYijLqjD8EOF9GcmU4mrRgePODHtfUtow6OBAx+Y4PVopoUVF3+yqJkziD5QHzkvewp58Wsdy6UH5Xh2uLWJuJQV1o5diXBjD3tbiQ7cpMBcgsY6BBKspkjrLtWxxtDnlEbHACMs4uBmSDyWn2hEl1AcXJ7EK8uQ5bm25N9rKgQaW1UAHHrrMUANPOyty5ma3nevVbRCx1wZeSCpCx3MTsbuJs+Tmgvc/QFBy+C0zDbMEIw3Mv9LOa35tDMP2WDhdg9PggGr0RGi/RSToZ/La3RJHl7tvCZ9XGkAMFcWUS5nF88YadAeTbpgamB/8ac=
  file:
    - builds/packed/electron.zip
    - builds/tdm-darwin-x64.7z
    - builds/tdm-win32-x64.7z
    - builds/tdm-win32-ia32.7z
    - builds/tdm-linux-x64.7z
    - builds/tdm-linux-ia32.7z
  on:
    repo: NOAO/downloader
